posts/urls.py
from django.conf.urls import url

from posts.views import HomeView, CreatePostView, MyPostsView, ChangePostStatusView, CountryAutocomplete, \
    like_share_ajax, DetailPostView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^post/new/$', CreatePostView.as_view(), name='post_create'),
    url(r'^my-posts/$', MyPostsView.as_view(), name='my_posts'),
    url(r'^my-posts/(?P<user_post_id>\w+)/(?P<status>0|1)/$',
        ChangePostStatusView.as_view(), name='status_change'),
    url(r'^country-autocomplete/$', CountryAutocomplete.as_view(), name='country_autocomplete'),
    url(r'^post/(?P<pk>\d+)/$', DetailPostView.as_view(), name='post_detail'),
    url(r'^post/like/$', like_share_ajax, name='like_share')
]

rest_api/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('allauth.urls')),
    url(r'^', include('accounts.urls', namespace='accounts')),
    url(r'^', include('posts.urls', namespace='posts')),
]

posts/models.py
import time
import datetime
import requests

from allauth.socialaccount.models import SocialToken
from django.db import models

import urllib.parse as urlparse

from django_countries.fields import CountryField
from embed_video.fields import EmbedVideoField

from accounts.models import MyUser
from posts.tasks import deactivate_post

POST_STATUS = (
    (0, 'Active'),
    (1, 'Deactivated')
)

GENDER_TARGETED = (
    (0, 'All'),
    (1, 'Male'),
    (2, 'Female')
)


class Country(models.Model):
    name = models.CharField(max_length=255)
    code = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Country'
        verbose_name_plural = 'Countries'


class Post(models.Model):
    url = models.CharField(max_length=2000)
    fb_post_id = models.IntegerField(blank=True, null=True)
    fb_user_id = models.IntegerField(blank=True, null=True)
    user_post_id = models.CharField(max_length=255, blank=True, null=True)
    post_starts = models.DateTimeField(default=datetime.datetime.now)
    post_ends = models.DateField(blank=True, null=True)
    post_status = models.IntegerField(default=0, choices=POST_STATUS)

    created_time = models.DateField(blank=True, null=True)
    message = models.CharField(max_length=4000, blank=True, null=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    description = models.CharField(max_length=255, blank=True, null=True)
    caption = models.CharField(max_length=255, blank=True, null=True)
    picture_url = models.CharField(max_length=2000, blank=True, null=True)
    video_url = EmbedVideoField(blank=True, null=True)
    video_fb = models.URLField(max_length=500, blank=True, null=True)
    link_url = models.CharField(max_length=2000, blank=True, null=True)

    gender_targeted = models.IntegerField(default=0, choices=GENDER_TARGETED)
    countries_targeted = models.ManyToManyField(Country, blank=True, related_name="posts_countries")

    likes = models.ManyToManyField(MyUser, related_name="likes", blank=True, through='LikesExtra')
    shares = models.ManyToManyField(MyUser, related_name="shares", blank=True, through='SharesExtra')
    shared_with_friends = models.PositiveIntegerField(default=0)
    my_user = models.ForeignKey(MyUser)

    def __str__(self):
        return str(self.id)

    @property
    def total_likes(self):
        return self.likes.count()

    @property
    def total_shares(self):
        return self.shares.count()

    def save(self, *args, **kwargs):
        url = self.url
        parsed = urlparse.urlparse(url)
        user = self.my_user
        access_token = SocialToken.objects.get(account__user=user, account__provider='facebook')

        if "videos" in parsed.path:
            split_list = parsed.path.split("/")

            # if "vb" in parsed.path
            if len(split_list) == 6:
                self.fb_post_id = int(split_list[4])
                self.fb_user_id = int(split_list[1])
                self.user_post_id = "_".join([str(self.fb_user_id), str(self.fb_post_id)])
            elif len(split_list) == 5:
                self.fb_post_id = int(split_list[3])
                if split_list[1].isdigit():
                    self.fb_user_id = int(split_list[1])
                    self.user_post_id = "_".join([str(self.fb_user_id), str(self.fb_post_id)])
                else:
                    fb_page_username = str(split_list[1])
                    r = requests.get('https://graph.facebook.com/{0}?access_token={1}'.format(fb_page_username, access_token))
                    fb_user_id = r.json()['id']
                    self.fb_user_id = int(fb_user_id)
                    self.user_post_id = "_".join([fb_user_id, split_list[3]])
        elif "photo.php" in parsed.path:
            self.fb_post_id = int(urlparse.parse_qs(parsed.query)['fbid'][0])
            self.fb_user_id = int(urlparse.parse_qs(parsed.query)['set'][0].split('.')[-1])
            self.user_post_id = "_".join([str(self.fb_user_id), str(self.fb_post_id)])
        elif "photos" in parsed.path:
            self.fb_post_id = int(parsed.path.split('.')[-1].split('/')[1])
            self.fb_user_id = int(parsed.path.split('.')[-1].split('/')[0])
            self.user_post_id = "_".join([str(self.fb_user_id), str(self.fb_post_id)])
        elif "story_fbid" in parsed.query:
            self.fb_post_id = int(urlparse.parse_qs(parsed.query)['story_fbid'][0])
            self.fb_user_id = int(urlparse.parse_qs(parsed.query)['id'][0])
            self.user_post_id = "_".join([str(self.fb_user_id), str(self.fb_post_id)])
        elif "posts" in parsed.path:
            self.fb_post_id = int(parsed.path.split("/")[-1])
            self.fb_user_id = int(user.socialaccount_set.all()[0].uid)
            self.user_post_id = "_".join([str(self.fb_user_id), str(self.fb_post_id)])

        r = requests.get('https://graph.facebook.com/{0}?fields=message,created_time,name,description,caption,attachments,source&'
                         'access_token={1}'.format(self.user_post_id, access_token))
        rjson = r.json()

        if "message" in rjson:
            self.message = rjson['message']
        if "name" in rjson:
            self.name = rjson['name']
        if "description" in rjson:
            self.description = rjson['description']
        if "caption" in rjson:
            self.caption = rjson['caption']
        if "source" in rjson:
            video = rjson['source']
            if "video.xx.fbcdn.net" in video:
                self.video_fb = video
            else:
                self.video_url = video
        if "attachments" in rjson:
            self.picture_url = rjson['attachments']['data'][0]['media']['image']['src']
        if "link" in rjson:
            self.link_url = rjson['link']

        create_task = False
        if self.id is None:
            create_task = True

        super(Post, self).save(*args, **kwargs)

        if create_task:
            post_starts = self.post_starts
            post_ends = self.post_ends
            date_range = post_ends - post_starts.date()
            final_date = post_starts + date_range
            deactivate_post.apply_async(args=[self.id], eta=final_date)

    class Meta:
        ordering = ["-post_starts"]


class SharedPost(models.Model):
    original = models.ForeignKey(Post, blank=True, related_name="original_post")
    shared_id = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.shared_id


class LikesExtra(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    date = models.DateField(default=datetime.date.today)
    timestamp = models.IntegerField(default=int(time.time()))

    def __str__(self):
        return str(self.post.id)


class SharesExtra(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    date = models.DateField(default=datetime.date.today)
    timestamp = models.IntegerField(default=int(time.time()))
    reach = models.PositiveIntegerField(default=0)

    def __str__(self):
        return str(self.post.id)

posts/views.py
import json
import time
import requests
from allauth.socialaccount.models import SocialToken, SocialAccount
import datetime
from dal import autocomplete
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import RedirectView
from django.views.generic import UpdateView
from el_pagination.views import AjaxListView

from accounts.mixins import CompanyRequiredMixin, AuthorRequiredMixin, ClickerRequiredMixin
from posts.forms import PostForm
from posts.models import Post, Country, SharedPost, LikesExtra, SharesExtra


class HomeView(LoginRequiredMixin, AjaxListView):
    template_name = "home.html"
    page_template = "single_post.html"
    model = Post

    def get_queryset(self):
        my_country = self.request.user.country.name
        my_gender = self.request.user.gender
        print(my_gender)
        if my_gender == "UNKNOWN":
            gender = 0
        elif my_gender == "MALE":
            gender = 1
        elif my_gender == "FEMALE":
            gender = 2
        print(gender)
        return Post.objects.filter(post_status=0). \
            filter(Q(countries_targeted__name__contains=my_country) | Q(countries_targeted__isnull=True) & Q(
            gender_targeted=0) | Q(gender_targeted=gender))

    def get(self, *args):
        if self.request.user.is_authenticated:
            if self.request.user.is_undefined:
                return redirect(reverse_lazy('accounts:pick_role'))
            else:
                return super(HomeView, self).get(*args)
        else:
            return super(HomeView, self).get(*args)


class CreatePostView(LoginRequiredMixin, CompanyRequiredMixin, CreateView):
    template_name = "post_create.html"
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('posts:home')

    def get_initial(self):
        return {'my_user': self.request.user}

    def get_form_kwargs(self):
        kwargs = super(CreatePostView, self).get_form_kwargs()
        kwargs.update({'post_user': self.request.user})
        return kwargs


class MyPostsView(LoginRequiredMixin, CompanyRequiredMixin, ListView):
    template_name = "my_posts.html"
    model = Post

    def get_queryset(self):
        return Post.objects.filter(my_user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super(MyPostsView, self).get_context_data(**kwargs)
        context['todays_date'] = datetime.datetime.now().date()
        return context


class DetailPostView(LoginRequiredMixin, AuthorRequiredMixin, DetailView):
    template_name = "post_detail.html"
    model = Post

    def authors(self):
        return [self.get_object().my_user]

    def get_context_data(self, **kwargs):
        context = super(DetailPostView, self).get_context_data(**kwargs)
        post = get_object_or_404(Post, id=self.kwargs.get('pk'))
        try:
            start_date = int(post.likesextra_set.first().timestamp)
        except AttributeError:
            start_date = time.time()

        last_date = ""
        likes = []
        like_extras = post.likesextra_set.all()
        for like in like_extras:
            if str(like.date) != last_date:
                likes.append([like.timestamp * 1000, int(like_extras.filter(date=like.date).count())])
                last_date = str(like.date)

        last_date = ""
        shares = []
        share_extras = post.sharesextra_set.all()
        for share in share_extras:
            if str(share.date) != last_date:
                shares.append([share.timestamp *1000, int(share_extras.filter(date=share.date).count())])
                last_date = str(share.date)

        context['start_date'] = start_date
        context['todays_date'] = datetime.datetime.now().date()
        context['likes'] = likes
        context['shares'] = shares
        return context


class ChangePostStatusView(LoginRequiredMixin, CompanyRequiredMixin, RedirectView):
    url = reverse_lazy('posts:my_posts')

    def get(self, request, *args, **kwargs):
        post = get_object_or_404(Post, user_post_id=kwargs.get('user_post_id'))

        if kwargs.get('status') == '0' and post.my_user == self.request.user:
            post.post_status = 1
            post.save()
        elif kwargs.get('status') == '1' and post.my_user == self.request.user and post.my_user.credit > 0:
            post.post_status = 0
            post.save()
        else:
            messages.warning(request, "You need more credit in order to activate your posts.")

        return super().get(request, *args, **kwargs)

    # def get_redirect_url(self, *args, **kwargs):
    #     print(self.request)
    #     post_id = self.kwargs.get('pk')
    #     print(post_id)
    #     if post_id:
    #         print(post_id)
    #     else:
    #         return reverse_lazy('posts:my_posts')


class CountryAutocomplete(autocomplete.Select2QuerySetView):
    def get_result_label(self, item):
        output = u'<img src="http://localhost:8000/static/flags/{0}.gif" ' \
                 u'style="padding-bottom:2px;"> {1}'.format(item.code, item.name)
        return output

    def get_queryset(self):
        if not self.request.user.is_authenticated():
            return Country.objects.none()

        qs = Country.objects.all()

        if self.q:
            qs = qs.filter(name__istartswith=self.q)

        return qs


def like_share_ajax(request):
    if request.method == 'POST' and request.is_ajax():
        post_id = request.POST.get('post_id', '')
        action = request.POST.get('action', '')
        user = request.user
        post = get_object_or_404(Post, id=post_id)

        if action == "share":
            message = request.POST.get('message', '')
            user_friends = user.socialaccount_set.all()[0].extra_data['friends']['summary']['total_count']
            link = post.url
            access_token = SocialToken.objects.get(account__user=user, account__provider='facebook')
            data = {'message': message, 'link': link, 'access_token': access_token}
            r = requests.post('https://graph.facebook.com/me/feed', params=data)
            response = json.loads(r.text)

            try:
                shared_id = response['id']
            except TypeError:
                shared_id = ""
            if shared_id:
                SharedPost(original=post, shared_id=shared_id).save()

            shares_extra = SharesExtra(user=user, post=post, reach=int(user_friends))
            shares_extra.save()
            post.shared_with_friends += user_friends
            post.save()
            post_owner = post.my_user
            post_owner.credit -= float(user_friends / 1000)
            post_owner.save()
            if post_owner.credit <= 0:
                for post in post_owner.post_set.all():
                    post.post_status = 1
                    post.save()

            user.credit += float(user_friends / 1000)
            user.save()
            user_total_credit = user.credit
            user_total_shares = user.shares.count()
            return JsonResponse(
                {'shares_count': post.shares.count(), 'post_id': post_id, 'user_total_shares': user_total_shares,
                 'user_total_credit': user_total_credit})

        if action == "like":
            if post.likes.filter(id=user.id).exists():
                LikesExtra.objects.get(user=user, post=post).delete()
                action = "disliked"
            else:
                likes_extra = LikesExtra(user=user, post=post)
                likes_extra.save()
                action = "liked"
            user_total_likes = user.likes.count()
            return JsonResponse(
                {'likes_count': post.total_likes, 'user_total_likes': user_total_likes, 'action': action})



            # else:
            #     return super(LikeShareView, self).get(self, request, *args, **kwargs)

            # def get(self, *args):
            #     access_token = SocialToken.objects.get(account__user=self.request.user, account__provider='facebook')
            #     social_acc = SocialAccount.objects.get(user=self.request.user)
            #     print(access_token)
            #     print(social_acc.uid)
            #     print(self.request.user)
            #
            #     r = requests.get('https://graph.facebook.com/{0}?access_token={1}'.format(social_acc.uid, access_token))
            #     print(r.url)
            #     print(r.text)
            #     print(r.json())
            #
            #     # data = {'message': 'Hello, World.', 'access_token': access_token}
            #     # r1 = requests.post('https://graph.facebook.com/me/feed', params=data)
            #     # print(r1.text)
            #
            #     return super(HomeView, self).get(*args)

posts/templates/my_posts.html
{% extends "base.html" %}
{% load css_extras %}

{% block content %}

    <section>
        <div class="container">
            {% for post in post_list %}
                <div class="row" style="border-bottom:1px solid #303030;padding:10px 10px;">
                    <div class="col-xs-2">
                        <a href="{% url "posts:post_detail" post.id %}"><img class="centered-and-cropped"
                                                                             src="{{ post.picture_url }}"
                                                                             style="width:100px;height:100px;"></a>
                    </div>
                    <div class="col-xs-4">
                        <p>{% if todays_date < post.post_ends %}Ends on {{ post.post_ends }}{% else %}
                            <span class="positive">Completed</span>{% endif %}</p>
                        <p>
                            <small>Promoted on {{ post.post_starts }}</small>
                        </p>
                        {% if todays_date < post.post_ends %}
                            <a href="{% url 'posts:status_change' user_post_id=post.user_post_id status=post.post_status %}">
                                {% if post.post_status == 0 %}
                                    <span class="positive">Active</span>
                                {% else %}
                                    <span class="negative">Deactivated</span>
                                {% endif %}
                            </a>
                        {% endif %}
                    </div>
                    <div class="col-xs-2">
                        <h4><i class="fa fa-thumbs-up positive" aria-hidden="true"
                               title="Likes Count"></i> {{ post.likes.count }}</h4>
                    </div>
                    <div class="col-xs-2">
                        <h4><i class="fa fa-share-alt yellow" aria-hidden="true"
                               title="Shares Count"></i> {{ post.shares.count }}</h4>
                    </div>
                    <div class="col-xs-2">
                        <h4><i class="fa fa-dollar" aria-hidden="true"
                               title="Promotion Cost"></i> {{ post.shared_with_friends|divide:"1000" }}</h4>
                    </div>
                </div>
            {% endfor %}
        </div>
    </section>

{% endblock %}


{% block customscripts %}

{% endblock customscripts %}

posts/templates/post_create.html
{% extends "base.html" %}
{% load css_extras %}
{% load staticfiles %}

{% block head %}
{% endblock head %}

{% block content %}

    <section>
        <div class="container">
            <div class="row" style="margin-top:50px;">
                <form method="POST" enctype="multipart/form-data">{% csrf_token %}

                    <div class="col-md-6 col-md-offset-3">
                        {% for error in form.non_field_errors %}
                            <p class="text-center negative">{{ error }}</p>
                        {% endfor %}
                        {% render_field form.url "url" "Link Your Facebook Post Here" "form-input" "form-label" %}
                        {% render_field form.post_ends "post_ends" "Promote This Post Until" "form-input" "form-label" %}
                        {% render_field form.gender_targeted "gender_targeted" "Gender" "form-input" "form-label" %}
                        {% render_field form.countries_targeted "countries_targeted" "Countries" "form-input" "form-label" %}
                    </div>

                    {{ form.my_user.as_hidden }}

                    <div class="col-md-6 col-md-offset-3">
                        <input class="promote-button" type="submit" value="Promote a post">
                    </div>

                </form>

            </div>
        </div>
    </section>

{% endblock %}


{% block customscripts %}
    {{ form.media }}
    <script src="http://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
            integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
    <script>
        $(document).ready(function () {
            $("#id_url").attr("placeholder", "url");
            $("#datepicker").attr("placeholder", "date");
            $('#datepicker').datepicker({dateFormat: "yy-mm-dd", minDate: 1, orientation: "left"});
        });
    </script>
{% endblock customscripts %}

posts/templates/post_detail.html
{% extends "base.html" %}
{% load css_extras %}

{% block head %}
    <script src="http://code.highcharts.com/highcharts.js"></script>
{% endblock %}

{% block content %}
    <section>
        <div class="container">
            <div class="row" style="padding:30px 10px 30px 10px;">
                    <div class="col-xs-2">
                        <img class="centered-and-cropped" src="{{ post.picture_url }}" style="width:100px;height:100px;">
                    </div>
                    <div class="col-xs-4">
                        <p>{% if todays_date < post.post_ends %}Ends on {{ post.post_ends }}{% else %}<span style="color:green">Completed</span>{% if post.post_ends %}<small> ({{ post.post_ends|date:"M. d, Y" }})</small>{% endif %}{% endif %}</p>
                        <p><small>Promoted on {{ post.post_starts }}</small></p>
                        {% if todays_date < post.post_ends %}
                            <a href="{% url 'posts:status_change' user_post_id=post.user_post_id status=post.post_status %}"
                               class="">
                                {% if post.post_status == 0 %}
                                    <span style="color:green;">Active</span>
                                {% else %}
                                    <span style="color:red;">Deactivated</span>
                                {% endif %}
                            </a>
                        {% endif %}
                    </div>
                    <div class="col-xs-3">
                        <h4><i class="fa fa-dollar" aria-hidden="true" title="Promotion Cost"></i> {{  post.shared_with_friends|divide:"1000" }}</h4>
                        <h4><i class="fa fa-thumbs-up positive" aria-hidden="true" title="Likes Count"></i> {{ post.likes.count }}</h4>
                    </div>
                    <div class="col-xs-3">
                        <h4><i class="fa fa-share-alt yellow" aria-hidden="true" title="Shares Count"></i> {{ post.shares.count }}</h4>
                        <h4><i class="fa fa-user-circle-o yellow" aria-hidden="true" title="Shared Among"></i> {{ post.shared_with_friends }}</h4>
                    </div>
                    </div>
            <div class="row">
                <div id="container" style="width:100%; height:400px;"></div>
            </div>
            <div class="row" style="padding-top:30px;">
                <h4>People who shared this post</h4>
                {% for sharedpost in post.sharesextra_set.all %}
                    <div class="col-md-6">
                        <a href="{{ sharedpost.user.socialaccount_set.all.0.extra_data.link }}" target="_blank">
                            <p><img src="{{ sharedpost.user.socialaccount_set.all.0.get_avatar_url }}" width="30"
                                 height="30">
                            {{ sharedpost.user.first_name }} {{ sharedpost.user.last_name }}</p>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>

{% endblock %}


{% block customscripts %}
    <script>

        Highcharts.chart('container', {

            title: {
                text: 'Engagement Growth'
            },

{#            subtitle: {#}
{#                text: 'Source: thesolarfoundation.com'#}
{#            },#}

            credits: false,

            xAxis: {
                type: 'datetime',
                tickInterval: 24 * 3600 * 1000,
{#                dateTimeLabelFormats: {#}
{#                    day: '%d %b %Y'    //ex- 01 Jan 2016#}
{#                }#}
            },

            yAxis: {
                tickInterval: 1,
                title: {
                    text: 'Count'
                }
            },

            legend: {
                layout: 'vertical',
                align: 'right',
                verticalAlign: 'middle'
            },

            plotOptions: {
                series: {
                    pointInterval: 24 * 3600 * 1000, // one day
{#                    pointStart: Date.UTC(2011, 11, 22),#}
                    pointStart: 1000*{{ start_date }}
                }
            },

            tooltip: {
                xDateFormat: '%Y-%m-%d'
            },

            series: [{
                name: 'Likes',
                color: '#97CE68',
                data: {{ likes }}
            }, {
                name: 'Shares',
                color: '#f1c40f',
                data: {{ shares }}
            }]
        });
    </script>
{% endblock %}

posts/templates/single_post.html
{% load embed_video_tags %}
{% load el_pagination_tags %}

{% paginate 5 post_list %}
{% for post in post_list %}
    <div class="row">
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-1"></div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-10">
            <div class="row">
                <div class="col-lg-8 col-md-10 col-sm-12 single-post"
                     {% if forloop.last %}style="border-bottom: 1px solid silver;"{% endif %}>
                    <div class="post-header">
                        <img src="{{ post.my_user.socialaccount_set.all.0.get_avatar_url }}"
                             style="width:40px; height:40px;">
                        <a target="_blank"
                           href="{{ post.my_user.socialaccount_set.all.0.extra_data.link }}">
                            {{ post.my_user.socialaccount_set.all.0.extra_data.name }}</a>
                        shared a <a target="_blank" href="{{ post.url }}">
                        link</a> on
                        {{ post.post_starts|date:"j M h:i a" }}
                    </div>

                    {% if post.message %}
                        <div class="post-message" style="margin: 10px 0px;">
                            {{ post.message }}
                        </div>
                    {% else %}
                        <br>
                    {% endif %}

                    <div class="post-body">
                        {% if post.video_url %}
                            {% video post.video_url 'small' %}
                        {% elif post.video_fb %}
                            <video src="{{ post.video_fb }}" controls></video>
                        {% elif post.picture_url %}
                            <img src="{{ post.picture_url }}" class="img-responsive">
                        {% endif %}
                        {% if post.name != "Timeline Photos" and post.name != null and "cover photo" not in post.name %}
                            <h4>{{ post.name }}</h4>
                        {% endif %}
                        {% if post.description %}
                            <p>{{ post.description }}</p>
                        {% endif %}
                        {% if post.caption %}
                            <p>{{ post.caption | upper }}</p>
                        {% endif %}
                        <br>
                    </div>
                    {% if user.is_clicker %}
                        <div>
                            <button id="{{ post.id }}" type="button"
                                    class="btn like-button {% if user in post.likes.all %}like-button-active{% endif %}">
                                {% if user in post.likes.all %}Liked{% else %}Like{% endif %}
                                | {{ post.total_likes }}</button>
                            <button id="{{ post.id }}" type="button"
                                    class="btn share-button {% if user in post.shares.all %}share-button-active{% endif %}"
                                    {% if user in post.shares.all %}disabled{% endif %}>
                                {% if user in post.shares.all %}Shared{% else %}Share{% endif %}
                                | {{ post.total_shares }}</button>
                        </div><br>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endfor %}

{% show_more %}