accounts/urls.py
from django.conf.urls import url

from accounts.views import PickRoleView, ProfileView

urlpatterns = [
    url(r'registration', PickRoleView.as_view(), name='pick_role'),
    url(r'profile/$', ProfileView.as_view(), name='profile')
]

posts/urls.py
from django.conf.urls import url

from posts.views import HomeView, CreatePostView, MyPostsView, ChangePostStatusView, CountryAutocomplete, \
    like_share_ajax, DetailPostView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^post/new/$', CreatePostView.as_view(), name='post_create'),
    url(r'^my-posts/$', MyPostsView.as_view(), name='my_posts'),
    url(r'^my-posts/(?P<user_post_id>\w+)/(?P<status>0|1)/$',
        ChangePostStatusView.as_view(), name='status_change'),
    url(r'^country-autocomplete/$', CountryAutocomplete.as_view(), name='country_autocomplete'),
    url(r'^post/(?P<pk>\d+)/$', DetailPostView.as_view(), name='post_detail'),
    url(r'^post/like/$', like_share_ajax, name='like_share')
]

rest_api/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('allauth.urls')),
    url(r'^', include('accounts.urls', namespace='accounts')),
    url(r'^', include('posts.urls', namespace='posts')),
]

accounts/models.py
from allauth.account.signals import user_signed_up
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import pre_save
from django.contrib.auth.models import AbstractUser
from django_countries import countries
from django_countries.fields import CountryField


class MyUser(AbstractUser):

    roles = (
        ('UNDEFINED', 'Undefined'),
        ('CLICKER', 'Clicker'),
        ('COMPANY', 'Company'),
    )

    gender = (
        ('UNKNOWN', 'Unknown'),
        ('MALE', 'Male'),
        ('FEMALE', 'Female'),
    )

    role = models.CharField(max_length=255, choices=roles, default='UNDEFINED')
    gender = models.CharField(max_length=255, choices=gender, default='UNKNOWN')
    country = CountryField(blank=True, null=True)
    credit = models.FloatField(default=0.0)

    @property
    def is_undefined(self):
        return self.role == 'UNDEFINED'

    @property
    def is_clicker(self):
        return self.role == 'CLICKER'

    @property
    def is_company(self):
        return self.role == 'COMPANY'


@receiver(pre_save, sender=MyUser)
def update_username_from_email(sender, instance, **kwargs):
    instance.username = instance.email


@receiver(user_signed_up)
def set_fb_uid(sender, **kwargs):
    user = kwargs.pop('user')
    extra_data = user.socialaccount_set.filter(provider='facebook')[0].extra_data
    try:
        country = extra_data['location']['location']['country']
    except KeyError:
        country = ""
    gender = extra_data['gender']

    if gender == 'male':
        user.gender = 'MALE'
    elif gender == 'female':
        user.gender = 'FEMALE'
    if country:
        country_code = countries.by_name(country)
        user.country = country_code
    user.save()

accounts/forms.py
from django import forms


# class MySignupForm(forms.Form):
#     first_name = forms.CharField(max_length=30, label='First name')
#     last_name = forms.CharField(max_length=30, label='Last name')
#
#     def signup(self, request, user):
#         user.first_name = self.cleaned_data['first_name']
#         user.last_name = self.cleaned_data['last_name']
#         user.save()

accounts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.shortcuts import redirect
from django.urls import reverse
from django.urls import reverse_lazy
from django.views.generic import DetailView
from django.views.generic import TemplateView

from accounts.models import MyUser


class PickRoleView(TemplateView):
    template_name = "pick_role.html"
    success_url = reverse_lazy('posts:home')

    def get(self, *args):
        if self.request.user.is_clicker or self.request.user.is_company:
            return redirect(reverse_lazy('posts:home'))
        else:
            return super(PickRoleView, self).get(*args)

    def post(self, request, *args, **kwargs):
        if request.is_ajax():
            role_picked = request.POST.get('role_picked', '')
            if "client" in role_picked:
                user = MyUser.objects.get(id=self.request.user.id)
                user.role = "CLICKER"
                user.save()

            if "company" in role_picked:
                user = MyUser.objects.get(id=self.request.user.id)
                user.role = "COMPANY"
                user.save()
            return HttpResponseRedirect(self.success_url)

        else:
            return super(PickRoleView, self).get(self, request, *args, **kwargs)


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "profile.html"
    model = MyUser

    def post(self, request, *args, **kwargs):
        if request.is_ajax():
            action = request.POST.get('action', '')
            user = request.user
            print(action)
            if action == "Deposit":
                amount = request.POST.get('amount', 0)
                user.credit += float(amount)
                user.save()
                messages.success(request, "You have successfully deposited {} credits.".format(amount))
                return JsonResponse({'credit': user.credit})
            elif action == "Withdraw":
                amount = user.credit
                user.credit = 0.0
                user.save()
                messages.success(request, "You have successfully withdrew {} credits.".format(amount))
                return JsonResponse({'credit': user.credit})
        else:
            return super(ProfileView, self).get(self, request, *args, **kwargs)

accounts/templates/pick_role.html
{% extends "base.html" %}

{% load i18n %}
{% load account socialaccount %}

{% block head_title %}{% trans "Pick role" %}{% endblock %}
{% block body_css %}login-body{% endblock body_css %}

{% block content %}
    <section>
        <div class="container">
            <div class="row" style="margin-top:250px;">
                <div class="col-sm-12 text-center">
                    <h2>Let's get started!</h2>
                    <h2>First, tell us what you're looking for.</h2>
                </div>
            </div>
            <form method="POST">{% csrf_token %}
                <div class="row" style="margin-top:50px;">
                    <div class="col-sm-6 text-center">
                        <h4 class="text-center yellow">I want to share others posts</h4>
                        <br>
                        <button id="client_button" class="role-btn btn-1a sharp" type="submit" value="client">Clicker
                        </button>
                    </div>
                    <div class="col-sm-6 text-center">
                        <h4 class="text-center yellow">I want to boost my posts</h4>
                        <br>
                        <button id="company_button" class="role-btn btn-1a sharp" type="submit" value="company">Booster
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </section>
{% endblock %}

{% block customscripts %}
    <script>
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie != '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    if (cookie.substring(0, name.length + 1) == (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        $(".btn-1a").click(function(e){
            e.preventDefault();
            var csrftoken = getCookie('csrftoken');
            var role_picked = $(this).attr('value');

            $.ajax({
                url:'{% url 'accounts:pick_role' %}',
                type:'POST',
                data:{
                    role_picked: role_picked,
                    csrfmiddlewaretoken: csrftoken
                },
                success: function(){
                    window.location.reload(true);
                },
            });
        });

    </script>
{% endblock customscripts %}

accounts/templates/profile.html
{% extends "base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Profile" %}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row text-center">
            {% if user.is_clicker %}
                <div class="col-xs-12">
                    <h3>You are currenty having <span id="credit">{{ user.credit }}</span> credit on your account.</h3>
                    {% if user.credit > 0 %}
                    <h3>You can withdraw it.</h3>
                    <input class="withdraw-deposit" type="submit" value="Withdraw" style="width: 13%">
                        {% else %}
                        <h3>Come back when you have more to withraw.</h3>
                        {% endif %}
                </div>
            {% elif user.is_company %}
                <div>
                    <h3>You are currenty having <span id="credit">{{ user.credit }}</span> credit on your account.</h3>
                    <h3>Deposit more <i class="fa fa-dollar"></i> <input type="number" name="deposit" value="5" min="5" max="100"></h3>
                    <br>
                    <input class="withdraw-deposit" type="submit" value="Deposit" style="width: 13%">
                </div>
            {% endif %}
        </div>
    </div>

{% endblock %}

{% block customscripts %}
    <script>
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie != '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    if (cookie.substring(0, name.length + 1) == (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        $(".withdraw-deposit").click(function () {
            var csrftoken = getCookie('csrftoken');
            var action = this.value;
            var amount = 0;

            if (action == "Deposit") {
                amount = $('input[name="deposit"]').val();
            }

            $.ajax({
                url: '{% url 'accounts:profile' %}',
                type: 'POST',
                data: {
                    action: action,
                    amount: amount,
                    csrfmiddlewaretoken: csrftoken
                },
                dataType: 'json',
                success: function (response) {
                    $('#credit').html(response.credit);
                    location.reload()
                }
            });
        });
    </script>
{% endblock customscripts %}