accounts/urls.py
from django.conf.urls import url

from accounts.views import PickRoleView, ProfileView

urlpatterns = [
    url(r'registration', PickRoleView.as_view(), name='pick_role'),
    url(r'profile/$', ProfileView.as_view(), name='profile')
]

posts/urls.py
from django.conf.urls import url

from posts.views import HomeView, CreatePostView, MyPostsView, ChangePostStatusView, CountryAutocomplete, \
    like_share_ajax, DetailPostView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^post/new/$', CreatePostView.as_view(), name='post_create'),
    url(r'^my-posts/$', MyPostsView.as_view(), name='my_posts'),
    url(r'^my-posts/(?P<user_post_id>\w+)/(?P<status>0|1)/$',
        ChangePostStatusView.as_view(), name='status_change'),
    url(r'^country-autocomplete/$', CountryAutocomplete.as_view(), name='country_autocomplete'),
    url(r'^post/(?P<pk>\d+)/$', DetailPostView.as_view(), name='post_detail'),
    url(r'^post/like/$', like_share_ajax, name='like_share')
]

rest_api/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('allauth.urls')),
    url(r'^', include('accounts.urls', namespace='accounts')),
    url(r'^', include('posts.urls', namespace='posts')),
]

posts/models.py
import time
import datetime
import requests

from allauth.socialaccount.models import SocialToken
from django.db import models

import urllib.parse as urlparse

from django_countries.fields import CountryField
from embed_video.fields import EmbedVideoField

from accounts.models import MyUser
from posts.tasks import deactivate_post

POST_STATUS = (
    (0, 'Active'),
    (1, 'Deactivated')
)

GENDER_TARGETED = (
    (0, 'All'),
    (1, 'Male'),
    (2, 'Female')
)


class Country(models.Model):
    name = models.CharField(max_length=255)
    code = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Country'
        verbose_name_plural = 'Countries'


class Post(models.Model):
    url = models.CharField(max_length=2000)
    fb_post_id = models.IntegerField(blank=True, null=True)
    fb_user_id = models.IntegerField(blank=True, null=True)
    user_post_id = models.CharField(max_length=255, blank=True, null=True)
    post_starts = models.DateTimeField(default=datetime.datetime.now)
    post_ends = models.DateField(blank=True, null=True)
    post_status = models.IntegerField(default=0, choices=POST_STATUS)

    created_time = models.DateField(blank=True, null=True)
    message = models.CharField(max_length=4000, blank=True, null=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    description = models.CharField(max_length=255, blank=True, null=True)
    caption = models.CharField(max_length=255, blank=True, null=True)
    picture_url = models.CharField(max_length=2000, blank=True, null=True)
    video_url = EmbedVideoField(blank=True, null=True)
    video_fb = models.URLField(max_length=500, blank=True, null=True)
    link_url = models.CharField(max_length=2000, blank=True, null=True)

    gender_targeted = models.IntegerField(default=0, choices=GENDER_TARGETED)
    countries_targeted = models.ManyToManyField(Country, blank=True, related_name="posts_countries")

    likes = models.ManyToManyField(MyUser, related_name="likes", blank=True, through='LikesExtra')
    shares = models.ManyToManyField(MyUser, related_name="shares", blank=True, through='SharesExtra')
    shared_with_friends = models.PositiveIntegerField(default=0)
    my_user = models.ForeignKey(MyUser)

    def __str__(self):
        return str(self.id)

    @property
    def total_likes(self):
        return self.likes.count()

    @property
    def total_shares(self):
        return self.shares.count()

    def save(self, *args, **kwargs):
        url = self.url
        parsed = urlparse.urlparse(url)
        user = self.my_user
        access_token = SocialToken.objects.get(account__user=user, account__provider='facebook')

        if "videos" in parsed.path:
            split_list = parsed.path.split("/")

            # if "vb" in parsed.path
            if len(split_list) == 6:
                self.fb_post_id = int(split_list[4])
                self.fb_user_id = int(split_list[1])
                self.user_post_id = "_".join([str(self.fb_user_id), str(self.fb_post_id)])
            elif len(split_list) == 5:
                self.fb_post_id = int(split_list[3])
                if split_list[1].isdigit():
                    self.fb_user_id = int(split_list[1])
                    self.user_post_id = "_".join([str(self.fb_user_id), str(self.fb_post_id)])
                else:
                    fb_page_username = str(split_list[1])
                    r = requests.get('https://graph.facebook.com/{0}?access_token={1}'.format(fb_page_username, access_token))
                    fb_user_id = r.json()['id']
                    self.fb_user_id = int(fb_user_id)
                    self.user_post_id = "_".join([fb_user_id, split_list[3]])
        elif "photo.php" in parsed.path:
            self.fb_post_id = int(urlparse.parse_qs(parsed.query)['fbid'][0])
            self.fb_user_id = int(urlparse.parse_qs(parsed.query)['set'][0].split('.')[-1])
            self.user_post_id = "_".join([str(self.fb_user_id), str(self.fb_post_id)])
        elif "photos" in parsed.path:
            self.fb_post_id = int(parsed.path.split('.')[-1].split('/')[1])
            self.fb_user_id = int(parsed.path.split('.')[-1].split('/')[0])
            self.user_post_id = "_".join([str(self.fb_user_id), str(self.fb_post_id)])
        elif "story_fbid" in parsed.query:
            self.fb_post_id = int(urlparse.parse_qs(parsed.query)['story_fbid'][0])
            self.fb_user_id = int(urlparse.parse_qs(parsed.query)['id'][0])
            self.user_post_id = "_".join([str(self.fb_user_id), str(self.fb_post_id)])
        elif "posts" in parsed.path:
            self.fb_post_id = int(parsed.path.split("/")[-1])
            self.fb_user_id = int(user.socialaccount_set.all()[0].uid)
            self.user_post_id = "_".join([str(self.fb_user_id), str(self.fb_post_id)])

        r = requests.get('https://graph.facebook.com/{0}?fields=message,created_time,name,description,caption,attachments,source&'
                         'access_token={1}'.format(self.user_post_id, access_token))
        rjson = r.json()

        if "message" in rjson:
            self.message = rjson['message']
        if "name" in rjson:
            self.name = rjson['name']
        if "description" in rjson:
            self.description = rjson['description']
        if "caption" in rjson:
            self.caption = rjson['caption']
        if "source" in rjson:
            video = rjson['source']
            if "video.xx.fbcdn.net" in video:
                self.video_fb = video
            else:
                self.video_url = video
        if "attachments" in rjson:
            self.picture_url = rjson['attachments']['data'][0]['media']['image']['src']
        if "link" in rjson:
            self.link_url = rjson['link']

        create_task = False
        if self.id is None:
            create_task = True

        super(Post, self).save(*args, **kwargs)

        if create_task:
            post_starts = self.post_starts
            post_ends = self.post_ends
            date_range = post_ends - post_starts.date()
            final_date = post_starts + date_range
            deactivate_post.apply_async(args=[self.id], eta=final_date)

    class Meta:
        ordering = ["-post_starts"]


class SharedPost(models.Model):
    original = models.ForeignKey(Post, blank=True, related_name="original_post")
    shared_id = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.shared_id


class LikesExtra(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    date = models.DateField(default=datetime.date.today)
    timestamp = models.IntegerField(default=int(time.time()))

    def __str__(self):
        return str(self.post.id)


class SharesExtra(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    date = models.DateField(default=datetime.date.today)
    timestamp = models.IntegerField(default=int(time.time()))
    reach = models.PositiveIntegerField(default=0)

    def __str__(self):
        return str(self.post.id)

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Clicker</title>

    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" type="text/css">

    <link rel="stylesheet" href="{% static "css/simple-line-icons.css" %}" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700&amp;subset=latin-ext" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}">

    <link rel="stylesheet" href="{% static "css/styles.css" %}" type="text/css">


    {% block head %}

    {% endblock head %}

</head>

<body class="{% block body_css %}{% endblock body_css %}">

    {% if user.is_authenticated and user.role != "UNDEFINED" %}
    <section>
            <nav class="navbar navbar-default navbar-fixed-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{% url 'posts:home' %}">Clickr</a>
                    </div>
                    <div class="collapse navbar-collapse" id="myNavbar">
                        <ul class="nav navbar-nav">
                            <li class="{% if request.path == '/' %}active{% endif %}"><a href="{% url 'posts:home' %}">Home</a></li>
                            {% if user.is_company %}
                                <li class="{% if request.path == '/post/new/' %}active{% endif %}"><a href="{% url 'posts:post_create' %}">Promote</a></li>
                                <li class="{% if request.path == '/my-posts/' %}active{% endif %}"><a href="{% url 'posts:my_posts' %}">My Posts</a></li>
                            {% endif %}
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            {% if user.is_authenticated %}
                                <li class="navbar-brand" style="padding: 0px;"><img
                                        src="{{ user.socialaccount_set.all.0.get_avatar_url }}"></li>
                                <li><a href="{% url 'accounts:profile' %}">{{ user.socialaccount_set.all.0.extra_data.name }}</a></li>
                            {% endif %}
                            <li><a href="{% url 'account_logout' %}"><small class="glyphicon glyphicon-log-out"></small> logout</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
    </section>
    {% endif %}

    <section>
        {% if messages %}
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="messages-content">
                            <div class="messages-content-inner">
                                <div class="messages">
                                    {% for message in messages %}
                                        <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
                                            <a id="alert-message-close" href="#" class="close" data-dismiss="alert"
                                               aria-label="close">&times;</a>
                                            {{ message }}
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    </section>

{#<nav>#}
{#    <div>#}
{#        <div>#}
{#            <ul>#}
{#                {% if user.is_authenticated %}#}
{#                    <li>Hi {{ user.first_name }}</li>#}
{#                    <li><a href="{% url 'account_logout' %}">Sign Out</a></li>#}
{#                {% else %}#}
{#                    <li><a href="{% url 'account_login' %}">Sign In</a></li>#}
{#                    <li><a href="{% url 'account_signup' %}">Sign Up</a></li>#}
{#                {% endif %}#}
{#            </ul>#}
{#        </div>#}
{#    </div>#}
{#</nav>#}

{% block content %}

{% endblock content %}

    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>

{% block customscripts %}

{% endblock customscripts %}

</body>

</html>

templates/form_field.html
{% load css_extras %}

<div class="form-group {% if field.form_field.errors %}has-error{% endif %}">
    {% if field.label %}
        <label for="{{ field.name }}" class="{{ field.label_class }}">{{ field.label }}</label><br />
    {% endif %}

    {% if field.icon %}
        <div class="input-group">
    {% endif %}

    {% if field.additional_class %}
        {% with "form-control "|add:field.additional_class as field_class %}
            {{ field.form_field | addcss:field_class }}
        {% endwith %}
    {% else %}
        {{ field.form_field | addcss:"form-control" }}
    {% endif %}

    {% if field.icon %}
        <span class="input-group-addon"><a><i class="fa {{ field.icon }}"></i></a></span>
        </div>
    {% endif %}

    {% if field.form_field.errors %}
        <span>{{ field.form_field.errors.as_text }}</span>
    {% endif %}

</div>

templates/home.html
{% extends "base.html" %}
{% load staticfiles %}
{% load el_pagination_tags %}
{% load css_extras %}

{% block content %}

    <section>
        {% if user.is_clicker %}
            <div class="quick-info col-lg-offset-7 col-md-offset-8 col-md-2 hidden-sm hidden-xs"
                 style="left:20px;width:250px;background-color: white;">
                <h3><i class="fa fa-dollar" aria-hidden="true"></i><span id="user_credit" data-toggle="tooltip" title="account balance" data-placement="right"> {{ user.credit }}</span></h3>
                <h3><i class="fa fa-thumbs-up positive" aria-hidden="true"></i><span data-toggle="tooltip" title="total posts liked" data-placement="right"
                        id="user_total_likes"> {{ user.likes.count }}</span></h3>
                <h3><i class="fa fa-share-alt yellow" aria-hidden="true"></i><span data-toggle="tooltip" title="total posts shared" data-placement="right"
                        id="user_total_shares"> {{ user.shares.count }}</span></h3>
            </div>
        {% elif user.is_company %}
            <div class="quick-info col-lg-offset-7 col-md-offset-8 col-md-2 hidden-sm hidden-xs"
                 style="left:20px;width:250px;background-color: white;">
                <h3><i class="fa fa-dollar"></i><span data-toggle="tooltip" title="account balance" data-placement="right"> {{ user.credit }}</span></h3>
                <h3><i class="fa fa-hashtag" aria-hidden="true"></i><span data-toggle="tooltip" title="number of posts" data-placement="right"> {{ user.post_set.all.count }}</span></h3>
                <h3><i class="fa fa-thumbs-up positive" aria-hidden="true"></i><span data-toggle="tooltip" title="likes total" data-placement="right"> {{ user.post_set.all|get_sum:"likes" }}</span></h3>
                <h3><i class="fa fa-share-alt yellow" aria-hidden="true"></i><span data-toggle="tooltip" title="shares total" data-placement="right"
                        id="user_total_shares"> {{ user.post_set.all|get_sum:"shares" }}</span></h3>
            </div>
        {% endif %}
    </section>

    <section>
        <div class="container-fluid">
            {% include page_template %}
            <div id="share-modal" class="modal fade">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
{#                            <h2 class="modal-title" >Share</h2>#}
                        </div>
                        <form method="POST">
                            <div class="form-group">
                                <input type="text" class="form-control" name="share-message" placeholder="Say something about this..." style="border:none">
                            </div>
                        </form>
                        <div class="modal-body">
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn close-button" data-dismiss="modal">Close</button>
                            <button type="button" id="share-to-fb" class="btn share-to-fb-button" data-dismiss="modal">Share</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}


{% block customscripts %}
    {{ block.super }}
    <script src="{% static "js/el-pagination.js" %}"></script>
    <script>
        $.endlessPaginate({paginateOnScroll: true});

        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie != '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    if (cookie.substring(0, name.length + 1) == (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        $(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });

        $(".like-button").click(function () {
            var csrftoken = getCookie('csrftoken');
            var post_id = this.id;

            $.ajax({
                url: '{% url 'posts:like_share' %}',
                type: 'POST',
                data: {
                    action: "like",
                    post_id: post_id,
                    csrfmiddlewaretoken: csrftoken
                },
                dataType: 'json',
                context: this,
                success: function (response) {
                    var likes = response.likes_count;
                    $('#user_total_likes').html(" " + response.user_total_likes);
                    if (response.action == "disliked") {
                        $(this).html("Like | " + likes);
                        $(this).css("color", "white");
                        $(this).removeClass("like-button-active");
                    } else if (response.action == "liked") {
                        $(this).addClass("like-button-active");
                        $(this).html("Liked | " + likes);
                    }
                }
            });
        });

        var post_id = "";

        $(".share-button").click(function () {
            post_id = this.id;
            var img_url = $(this).closest('.row').find('.post-body').children('img').attr('src');
            var post_message = $(this).closest('.row').find('.post-message').html();
            $('.modal-body').html('<img src="' + img_url + '" class="img-responsive">');
            $('#share-modal').modal('show');
        });

        $("#share-to-fb").click(function () {
            var csrftoken = getCookie('csrftoken');
            var message = $('input[name="share-message"]').val();
            console.log(message);
            $.ajax({
                url: '{% url 'posts:like_share' %}',
                type: 'POST',
                data: {
                    action: "share",
                    message: message,
                    post_id: post_id,
                    csrfmiddlewaretoken: csrftoken
                },
                dataType: 'json',
                context: this,
                success: function (response) {
                    var post_id = response.post_id;
                    var $button = $('#' + post_id + ".share-button");
                    $('#user_total_shares').html(" " + response.user_total_shares);
                    $('#user_credit').html(" " + response.user_total_credit);
                    $button.addClass("share-button-active");
                    $button.prop("disabled", true);
                    $button.html("Shared | " + response.shares_count);
                }
            });
        });

    </script>
{% endblock customscripts %}